version: "3.9"
services:
  db:
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_DATABASE: dev
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    expose:
      - 3306

  rabbitmq:
    image: rabbitmq:3.9.10-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge